# romantic.py

SONGS = [
    "Ed Sheeran - Perfect",
    "Ed Sheeran - Thinking Out Loud",
    "Ed Sheeran - Photograph",
    "Ed Sheeran - Shape of You (Acoustic)",
    "John Legend - All of Me",
    "John Legend - Ordinary People",
    "Bruno Mars - Just The Way You Are",
    "Bruno Mars - Treasure",
    "Bruno Mars - When I Was Your Man",
    "Bruno Mars - Marry You",

    "The Weeknd - Die For You",
    "The Weeknd - Earned It",
    "The Weeknd - I Feel It Coming",
    "The Weeknd - Starboy (Slow Edit)",
    "Ariana Grande - Into You",
    "Ariana Grande - One Last Time",
    "Ariana Grande - Almost Is Never Enough",
    "Justin Bieber - Anyone",
    "Justin Bieber - Intentions",
    "Justin Bieber - Love Yourself",

    "Shawn Mendes - Treat You Better",
    "Shawn Mendes - Stitches",
    "Shawn Mendes - Mercy",
    "Shawn Mendes - In My Blood (Soft)",
    "Taylor Swift - Lover",
    "Taylor Swift - Enchanted",
    "Taylor Swift - You Are In Love",
    "Taylor Swift - Style (Acoustic)",
    "Taylor Swift - Fearless",
    "Taylor Swift - Wildest Dreams",

    "Zayn - Pillowtalk",
    "Zayn - Dusk Till Dawn",
    "Zayn - Better",
    "Sam Smith - Stay With Me",
    "Sam Smith - Lay Me Down",
    "Sam Smith - Too Good At Goodbyes (Romantic Edit)",
    "Maroon 5 - Sugar",
    "Maroon 5 - Girls Like You",
    "Maroon 5 - Memories",
    "Maroon 5 - She Will Be Loved",

    "One Direction - Night Changes",
    "One Direction - Little Things",
    "One Direction - Perfect",
    "Westlife - My Love",
    "Westlife - You Raise Me Up",
    "Westlife - Swear It Again",
    "Backstreet Boys - As Long As You Love Me",
    "Backstreet Boys - I Want It That Way",
    "Boyz II Men - End Of The Road",
    "Boyz II Men - I'll Make Love To You",

    "Akon - Right Now (Na Na Na)",
    "Akon - Beautiful",
    "Rihanna - Love On The Brain",
    "Rihanna - We Found Love (Slow)",
    "Chris Brown - With You",
    "Chris Brown - Forever",
    "Chris Brown - No Guidance",
    "Ne-Yo - Miss Independent",
    "Ne-Yo - So Sick",
    "Usher - You Got It Bad",

    "Lana Del Rey - Young And Beautiful",
    "Lana Del Rey - Summertime Sadness",
    "Lana Del Rey - Love",
    "Billie Eilish - Ocean Eyes",
    "Billie Eilish - Lovely",
    "Billie Eilish - Halley's Comet",
    "Halsey - Without Me (Love Edit)",
    "Halsey - Closer (Romantic Remix)",
    "Charlie Puth - We Don't Talk Anymore",
    "Charlie Puth - Attention (Slow)",

    "Alec Benjamin - Let Me Down Slowly",
    "Alec Benjamin - If We Have Each Other",
    "Lewis Capaldi - Someone You Loved",
    "Lewis Capaldi - Before You Go (Love Version)",
    "Lewis Capaldi - Hold Me While You Wait",
    "Sam Fischer - This City (Acoustic)",
    "Dean Lewis - Be Alright",
    "Dean Lewis - How Do I Say Goodbye",
    "Ruth B - Dandelions",
    "Ruth B - Lost Boy (Romantic Mix)",

    "Arijit Singh - Tum Hi Ho",
    "Arijit Singh - Channa Mereya",
    "Arijit Singh - Raabta",
    "Arijit Singh - Agar Tum Saath Ho",
    "Arijit Singh - Shayad",
    "Arijit Singh - Janam Janam",
    "Arijit Singh - Tera Ban Jaunga",
    "Atif Aslam - Tera Hone Laga Hoon",
    "Atif Aslam - Jeene Laga Hoon",
    "Atif Aslam - Tere Sang Yaara",

    "Shreya Ghoshal - Sun Raha Hai",
    "Shreya Ghoshal - Teri Ore",
    "Jubin Nautiyal - Tum Hi Aana",
    "Jubin Nautiyal - Humnava Mere",
    "Darshan Raval - Ek Tarfa (Love Edit)",
    "Darshan Raval - Asal Mein",
    "Neha Kakkar - Mile Ho Tum",
    "Neha Kakkar - Dilbar (Love Version)",
    "Vishal Mishra - Kaise Hua",
    "KK - Alvida (Love Version)",

    "Coldplay - Yellow (Love Edit)",
    "Coldplay - Paradise",
    "Coldplay - Magic",
    "Coldplay - A Sky Full Of Stars (Slow)",
    "Imagine Dragons - Next To Me",
    "Imagine Dragons - I Bet My Life",
    "Alan Walker - Faded (Romantic Remix)",
    "Alan Walker - Lily (Love Version)",
    "Kygo - Stole The Show",
    "Avicii - Without You (Love Edit)",

    "Post Malone - Circles",
    "Post Malone - I Like You",
    "Post Malone - Goodbyes (Love Version)",
    "Drake - Hold On We're Going Home",
    "Drake - Passionfruit",
    "Justin Timberlake - Mirrors",
    "Calvin Harris - Feel So Close (Romantic)",
    "Zedd - Stay",
    "Marshmello - Happier",
    "Clean Bandit - Symphony",

    "Conan Gray - Heather",
    "Conan Gray - Maniac (Love Edit)",
    "The Neighbourhood - Sweater Weather (Love Version)",
    "The 1975 - About You",
    "The 1975 - Somebody Else",
    "Birdy - Wings",
    "Birdy - Skinny Love (Love Mix)",
    "James Arthur - Say You Won't Let Go",
    "James Arthur - Naked",
    "James Arthur - Train Wreck"
]
