# sad.py

SONGS = [
    "Adele - Someone Like You",
    "Adele - Hello",
    "Adele - Easy On Me",
    "Adele - When We Were Young",
    "Passenger - Let Her Go",
    "Lewis Capaldi - Someone You Loved",
    "Lewis Capaldi - Before You Go",
    "Coldplay - Fix You",
    "Coldplay - The Scientist",
    "Coldplay - Sparks",

    "Linkin Park - Numb",
    "Linkin Park - In The End",
    "Linkin Park - Shadow Of The Day",
    "Linkin Park - One More Light",
    "Billie Eilish - When The Party's Over",
    "Billie Eilish - Everything I Wanted",
    "Billie Eilish - Happier Than Ever (Sad Edit)",
    "James Arthur - Say You Won't Let Go",
    "James Arthur - Train Wreck",
    "Shawn Mendes - In My Blood",

    "Sam Smith - Too Good At Goodbyes",
    "Sam Smith - I'm Not The Only One",
    "Sam Smith - Lay Me Down",
    "Ed Sheeran - Photograph",
    "Ed Sheeran - Perfect (Sad Version)",
    "Ed Sheeran - Supermarket Flowers",
    "The Weeknd - Call Out My Name",
    "The Weeknd - Die For You",
    "The Weeknd - Save Your Tears (Acoustic)",
    "Bruno Mars - When I Was Your Man",

    "Taylor Swift - Back To December",
    "Taylor Swift - All Too Well",
    "Taylor Swift - Exile",
    "Akon - Lonely",
    "Akon - Sorry, Blame It On Me",
    "Rihanna - Stay",
    "Justin Bieber - Ghost",
    "Justin Bieber - Lonely",
    "Sia - Breathe Me",
    "Sia - Chandelier (Sad Version)",

    "Arijit Singh - Tum Hi Ho",
    "Arijit Singh - Channa Mereya",
    "Arijit Singh - Agar Tum Saath Ho",
    "Arijit Singh - Shayad",
    "Arijit Singh - Tera Yaar Hoon Main",
    "Arijit Singh - Phir Le Aya Dil",
    "Atif Aslam - Tera Ban Jaunga",
    "Atif Aslam - Jeene Laga Hoon",
    "Atif Aslam - Tere Sang Yaara",
    "Atif Aslam - Dil Diyan Gallan",

    "Shreya Ghoshal - Sun Raha Hai",
    "Shreya Ghoshal - Teri Ore",
    "Jubin Nautiyal - Humnava Mere",
    "Jubin Nautiyal - Tum Hi Aana",
    "Darshan Raval - Asal Mein",
    "Darshan Raval - Ek Tarfa",
    "Vishal Mishra - Kaise Hua",
    "KK - Alvida",
    "KK - Yaara Re",
    "KK - Beete Lamhe",

    "Kishore Kumar - Zindagi Ka Safar",
    "Kishore Kumar - Tere Bina Zindagi Se",
    "Mukesh - Kabhi Kabhi Mere Dil Mein",
    "Mukesh - Jeena Yahan Marna Yahan",
    "Lata Mangeshkar - Lag Ja Gale",
    "Lata Mangeshkar - Tere Bina",
    "Mohammed Rafi - Kya Hua Tera Wada",
    "Jagjit Singh - Hothon Se Chhu Lo Tum",
    "Jagjit Singh - Tum Itna Jo Muskura Rahe Ho",
    "Sonu Nigam - Ab Mujhe Raat Din",

    "XXXTENTACION - Sad!",
    "XXXTENTACION - Jocelyn Flores",
    "XXXTENTACION - Changes",
    "XXXTENTACION - Moonlight",
    "Juice WRLD - Lucid Dreams",
    "Juice WRLD - Legends",
    "Juice WRLD - Robbery",
    "Juice WRLD - All Girls Are The Same",
    "NF - Let You Down",
    "NF - If You Want Love",

    "Post Malone - I Fall Apart",
    "Post Malone - Circles (Sad Version)",
    "Post Malone - Goodbyes",
    "Charlie Puth - See You Again",
    "Charlie Puth - Attention (Sad Piano)",
    "Alec Benjamin - Let Me Down Slowly",
    "Alec Benjamin - Water Fountain",
    "Halsey - Without Me",
    "Halsey - Gasoline",
    "Conan Gray - Heather",

    "One Direction - Little Things",
    "One Direction - Night Changes",
    "Westlife - My Love",
    "Westlife - Seasons In The Sun",
    "Backstreet Boys - Show Me The Meaning",
    "Boyce Avenue - Heaven",
    "James Blunt - Goodbye My Lover",
    "James Blunt - You're Beautiful",
    "Green Day - Good Riddance",
    "Avril Lavigne - I'm With You",

    "Maroon 5 - Memories",
    "Maroon 5 - She Will Be Loved",
    "Imagine Dragons - Demons",
    "Imagine Dragons - Bleeding Out",
    "Imagine Dragons - Next To Me",
    "Zayn - Dusk Till Dawn (Sad Edit)",
    "Zayn - Pillowtalk (Slow)",
    "Shawn Mendes - Mercy",
    "Shawn Mendes - Lost In Japan (Sad Edit)",
    "Justin Bieber - Purpose (Acoustic)",

    "Pink - What About Us",
    "Ariana Grande - Almost Is Never Enough",
    "Ariana Grande - One Last Time",
    "Selena Gomez - Lose You To Love Me",
    "Selena Gomez - Back To You",
    "Lana Del Rey - Summertime Sadness",
    "Lana Del Rey - Young And Beautiful",
    "Billie Eilish - Ocean Eyes",
    "Billie Eilish - Lovely",
    "Sia - Elastic Heart (Sad Version)",

    "Tears For Fears - Everybody Wants To Rule The World (Slow)",
    "Radiohead - Creep",
    "Radiohead - No Surprises",
    "Bon Iver - Skinny Love",
    "The Neighbourhood - Softcore",
    "The Neighbourhood - Sweater Weather (Sad Edit)",
    "Linkin Park - Crawling",
    "Coldplay - Yellow (Sad Version)",
    "Coldplay - Everglow",
    "Coldplay - Fix You (Live)",

    "Alan Walker - Faded (Sad Remix)",
    "Alan Walker - Alone",
    "Kygo - Firestone (Sad Version)",
    "Clean Bandit - Rather Be (Slow)",
    "Calvin Harris - Summer (Sad Edit)",
    "Avicii - Wake Me Up (Acoustic)",
    "Avicii - Without You",
    "Martin Garrix - Scared To Be Lonely",
    "David Guetta - Without You",
    "Zedd - Clarity (Sad Version)",

    "Hozier - Take Me To Church (Slow)",
    "Hozier - Cherry Wine",
    "Lewis Capaldi - Hold Me While You Wait",
    "Lewis Capaldi - Wish You The Best",
    "Sam Fischer - This City (Acoustic)",
    "Dean Lewis - Be Alright",
    "Dean Lewis - Waves",
    "Ruth B - Lost Boy",
    "Birdy - Skinny Love",
    "Birdy - Wings"
]
